### PR TITLE
FEAT!: draft of NGS analysis+archive script

### PR DESCRIPTION
**Pull request by ericksamera**
CHANGELOG
- draft for analysis+archive

TODO
- documentation
- test run
- force `fastqc` mamba env

### CODE REVIEW

**Comment by ericksamera** [comment]
@ksaulog i'm dumb and introduced some artifacts. Also added in a sanity check for dependencies (because I keep running this without being in the `fastqc` env).

Also added PhiX analysis cli arg, so far we don't run PhiX every time but I am assuming this will be changed in the near future to run by default.

let me know if you spot anything that doesn't belong and check the changelog for more yapping

**TODO:** docstrings!

**Review by ksaulog — COMMENTED** [review]
In check_dependencies, is installed_status returning an empty dict or am I illiterate

**Comment by ericksamera** [comment]
@ksaulog oh that's a remnant of another approach I did. Initially it went through, checked them all, and then returned a dict of version info and stuff for parsing.
Maybe in this implementation, it effectively doesn't return anything useful. Should raise RuntimeError if anything is amiss tho

**Comment by ericksamera** [comment]
@Ryn29 @ksaulog @PaddyKTaylor 
If anyone wants Python practice, we've got some docs to write lmao

**Pull request merged**
